# Generated by Django 5.2.17 on 2026-09-23 22:03

import uuid

import django.utils.timezone
from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "purpose",
                    models.CharField(
                        default="",
                        help_text="Purpose for this AccountToken record.",
                        max_length=255,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(
                        help_text="Token digest for this AccountToken record.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "email_snapshot",
                    models.EmailField(
                        help_text="Email snapshot for this AccountToken record.", max_length=254
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Expires at for this AccountToken record.",
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, help_text="Consumed at for this AccountToken record.", null=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="Revoked at for this AccountToken record.", null=True
                    ),
                ),
                (
                    "issued_auth_version",
                    models.PositiveIntegerField(
                        default=0, help_text="Issued auth version for this AccountToken record."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="Status for this RoleAssignment record.",
                        max_length=255,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Granted at for this RoleAssignment record.",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Revoked at for this RoleAssignment record.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Canonical lowercase login address.", max_length=254, unique=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="User-provided display name.", max_length=160),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Optional contact number.", max_length=32
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Successful email challenge timestamp.", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether authentication is allowed."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Access to the restricted operator admin site."
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Account creation date."
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en-gb", help_text="Language preference.", max_length=12
                    ),
                ),
                (
                    "auth_version",
                    models.PositiveIntegerField(
                        default=0, help_text="Increment to invalidate prior sessions and tokens."
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
