# Generated by Django 5.2.17 on 2026-09-23 22:03

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_initial"),
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred display currency.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="accounttoken",
            name="user",
            field=models.ForeignKey(
                help_text="User for this AccountToken record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Granted by for this RoleAssignment record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="group",
            field=models.ForeignKey(
                help_text="Group for this RoleAssignment record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School for this RoleAssignment record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fees.school",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="user",
            field=models.ForeignKey(
                help_text="User for this RoleAssignment record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "created_at"], name="accounts_us_is_acti_b0061a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="user_email_casefold_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="accounttoken",
            index=models.Index(
                fields=["user", "purpose", "expires_at"], name="accounts_ac_user_id_4e518f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["school", "status", "user"], name="accounts_ro_school__9d7753_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", False), ("status", "active")),
                fields=("user", "group", "school"),
                name="role_school_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", True), ("status", "active")),
                fields=("user", "group"),
                name="role_global_active",
            ),
        ),
    ]
