# Generated by Django 5.2.17 on 2026-09-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accounttoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["verification", "password_reset"])),
                name="ck_accounttoken_purpos",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "revoked"])),
                name="ck_roleassignment_status",
            ),
        ),
    ]
