# Generated by Django 5.2.17 on 2026-09-23 22:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code for this Currency record.",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        default="",
                        help_text="Display name for this Currency record.",
                        max_length=255,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        default="", help_text="Symbol for this Currency record.", max_length=255
                    ),
                ),
                (
                    "minor_units",
                    models.PositiveIntegerField(
                        default=2, help_text="Minor units for this Currency record."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is active for this Currency record."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "data_kind",
                    models.CharField(
                        default="",
                        help_text="Data kind for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(
                        default="",
                        help_text="Source filename for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "source_sha256",
                    models.CharField(
                        default="",
                        help_text="Source sha256 for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        default="",
                        help_text="Source system for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="1",
                        help_text="Schema version for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "effective_cutover_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Effective cutover at for this ImportBatch record.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="uploaded",
                        help_text="Status for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "dry_run_report_key",
                    models.CharField(
                        blank=True,
                        help_text="Dry run report key for this ImportBatch record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        default="",
                        help_text="Source key for this ImportBatch record.",
                        max_length=255,
                    ),
                ),
                (
                    "totals",
                    models.JSONField(
                        blank=True, default=dict, help_text="Totals for this ImportBatch record."
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, help_text="Applied at for this ImportBatch record.", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Row number for this ImportRow record."
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External id for this ImportRow record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "row_digest",
                    models.CharField(
                        default="",
                        help_text="Row digest for this ImportRow record.",
                        max_length=255,
                    ),
                ),
                (
                    "encrypted_source_key",
                    models.TextField(
                        default="", help_text="Encrypted source key for this ImportRow record."
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation errors for this ImportRow record.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Status for this ImportRow record.",
                        max_length=255,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Target type for this ImportRow record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="Target id for this ImportRow record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, help_text="Applied at for this ImportRow record.", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "kind",
                    models.CharField(
                        default="email",
                        help_text="Kind for this OutboxMessage record.",
                        max_length=255,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="", help_text="Topic for this OutboxMessage record.", max_length=255
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text="Dedupe key for this OutboxMessage record.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        blank=True,
                        help_text="Aggregate type for this OutboxMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "aggregate_id",
                    models.CharField(
                        blank=True,
                        help_text="Aggregate id for this OutboxMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Template name for this OutboxMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "template_version",
                    models.CharField(
                        blank=True,
                        help_text="Template version for this OutboxMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "encrypted_payload_key",
                    models.TextField(
                        default="", help_text="Encrypted payload key for this OutboxMessage record."
                    ),
                ),
                (
                    "attachment_keys",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Attachment keys for this OutboxMessage record.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="pending",
                        help_text="State for this OutboxMessage record.",
                        max_length=255,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Attempt count for this OutboxMessage record."
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Next attempt at for this OutboxMessage record.",
                        null=True,
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Locked until for this OutboxMessage record.",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Sent at for this OutboxMessage record.", null=True
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider message id for this OutboxMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True,
                        help_text="Last error code for this OutboxMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "actor_snapshot",
                    models.CharField(
                        default="",
                        help_text="Actor snapshot for this AuditEvent record.",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        default="", help_text="Action for this AuditEvent record.", max_length=255
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        default="",
                        help_text="Target type for this AuditEvent record.",
                        max_length=255,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="Target id for this AuditEvent record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        default="",
                        help_text="Correlation id for this AuditEvent record.",
                        max_length=255,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Occurred at for this AuditEvent record.",
                    ),
                ),
                (
                    "redacted_changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Redacted changes for this AuditEvent record.",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        default="success",
                        help_text="Outcome for this AuditEvent record.",
                        max_length=255,
                    ),
                ),
                (
                    "ip_digest",
                    models.CharField(
                        blank=True,
                        help_text="Ip digest for this AuditEvent record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Actor for this AuditEvent record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
