# Generated by Django 5.2.17 on 2026-09-23 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("fees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School for this AuditEvent record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fees.school",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Approved by for this ImportBatch record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School for this ImportBatch record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fees.school",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="submitted_by",
            field=models.ForeignKey(
                help_text="Submitted by for this ImportBatch record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importrow",
            name="batch",
            field=models.ForeignKey(
                help_text="Batch for this ImportRow record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User for this OutboxMessage record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["school", "occurred_at"], name="core_audite_school__31e608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor", "occurred_at"], name="core_audite_actor_i_43737a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["target_type", "target_id"], name="core_audite_target__8673ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["correlation_id"], name="core_audite_correla_d2ebe4_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["school", "status", "created_at"], name="core_import_school__75fbf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["batch", "status"], name="core_import_batch_i_24dfab_idx"),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["target_type", "target_id"], name="core_import_target__66fa89_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="core_importrow_u0"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="core_outbox_state_f26a79_idx"
            ),
        ),
    ]
