# Generated by Django 5.2.17 on 2026-09-23 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("fees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["uploaded", "validated", "rejected", "applying", "completed", "failed"],
                    )
                ),
                name="ck_importbatch_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "valid", "invalid", "applied", "skipped"])
                ),
                name="ck_importrow_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["email", "task"])), name="ck_outboxmessage_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["pending", "processing", "sent", "retry", "dead_letter"])
                ),
                name="ck_outboxmessage_state",
            ),
        ),
    ]
