# Generated by Django 5.2.17 on 2026-09-23 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_state_constraints"),
        ("fees", "0002_state_constraints"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "won", "lost", "closed"])),
                name="ck_dispute_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicereservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "consumed", "released", "expired"])),
                name="ck_invoicereservatio_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner_kind__in", ["school", "platform"])),
                name="ck_merchantaccount_owner_",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("gateway__in", ["stripe", "paypal", "paynow", "bank_partner"])),
                name="ck_merchantaccount_gatewa",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment__in", ["test", "live"])),
                name="ck_merchantaccount_enviro",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "enabled", "restricted", "disabled"])
                ),
                name="ck_merchantaccount_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "created",
                            "pending",
                            "succeeded",
                            "failed",
                            "cancelled",
                            "partially_refunded",
                            "refunded",
                            "review",
                        ],
                    )
                ),
                name="ck_payment_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "created",
                            "submitting",
                            "unknown",
                            "pending",
                            "succeeded",
                            "failed",
                            "cancelled",
                        ],
                    )
                ),
                name="ck_paymentattempt_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("rendering_status__in", ["pending", "ready", "failed"])),
                name="ck_receipt_render",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "resolved", "accepted_variance"])),
                name="ck_reconciliationite_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "completed", "failed"])),
                name="ck_reconciliationrun_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "requested",
                            "approved",
                            "submitting",
                            "unknown",
                            "pending",
                            "succeeded",
                            "failed",
                            "rejected",
                        ],
                    )
                ),
                name="ck_refund_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlemententry",
            constraint=models.CheckConstraint(
                condition=models.Q(("beneficiary__in", ["school", "platform", "provider"])),
                name="ck_settlemententry_benefi",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlemententry",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["credit", "debit"])),
                name="ck_settlemententry_direct",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlemententry",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed", "reversed"])),
                name="ck_settlemententry_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "processing_status__in",
                        ["received", "processing", "processed", "retry", "dead_letter"],
                    )
                ),
                name="ck_webhookevent_proces",
            ),
        ),
    ]
