# Generated by Django 5.2.17 on 2026-09-23 22:03

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "code",
                    models.CharField(
                        default="", help_text="Code for this AcademicPeriod record.", max_length=255
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="",
                        help_text="Label for this AcademicPeriod record.",
                        max_length=255,
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(help_text="Starts on for this AcademicPeriod record."),
                ),
                ("ends_on", models.DateField(help_text="Ends on for this AcademicPeriod record.")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is active for this AcademicPeriod record."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "code",
                    models.CharField(
                        default="", help_text="Code for this FeeCategory record.", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", help_text="Name for this FeeCategory record.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="", help_text="Description for this FeeCategory record."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is active for this FeeCategory record."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code for this School record.", max_length=255, unique=True
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        default="", help_text="Legal name for this School record.", max_length=255
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        default="", help_text="Display name for this School record.", max_length=255
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Registration number for this School record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="ZW",
                        help_text="Country code for this School record.",
                        max_length=255,
                    ),
                ),
                (
                    "address",
                    models.TextField(default="", help_text="Address for this School record."),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Contact email for this School record.", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone for this School record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Status for this School record.",
                        max_length=255,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Reviewed at for this School record.", null=True
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(default="", help_text="Review reason for this School record."),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Requested by for this School record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reviewed by for this School record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supported_currencies",
                    models.ManyToManyField(
                        help_text="Supported currencies for this School record.", to="core.currency"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "code",
                    models.CharField(
                        default="", help_text="Code for this FeeSchedule record.", max_length=255
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, help_text="Revision for this FeeSchedule record."
                    ),
                ),
                (
                    "class_label",
                    models.CharField(
                        blank=True,
                        help_text="Class label for this FeeSchedule record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Amount for this FeeSchedule record.",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is active for this FeeSchedule record."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category for this FeeSchedule record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.feecategory",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency for this FeeSchedule record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="Period for this FeeSchedule record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.academicperiod",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School for this FeeSchedule record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.school",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feecategory",
            name="school",
            field=models.ForeignKey(
                help_text="School for this FeeCategory record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fees.school",
            ),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="school",
            field=models.ForeignKey(
                help_text="School for this AcademicPeriod record.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fees.school",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "admission_number",
                    models.CharField(
                        default="",
                        help_text="Admission number for this Student record.",
                        max_length=255,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        default="", help_text="Full name for this Student record.", max_length=255
                    ),
                ),
                (
                    "class_label",
                    models.CharField(
                        blank=True,
                        help_text="Class label for this Student record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Status for this Student record.",
                        max_length=255,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Verified at for this Student record.", null=True
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School for this Student record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.school",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Submitted by for this Student record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verified by for this Student record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "number",
                    models.CharField(
                        default="", help_text="Number for this Invoice record.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="draft", help_text="Status for this Invoice record.", max_length=255
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, help_text="Issued at for this Invoice record.", null=True
                    ),
                ),
                (
                    "due_on",
                    models.DateField(
                        blank=True, help_text="Due on for this Invoice record.", null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total amount for this Invoice record.",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "document_key",
                    models.CharField(
                        blank=True,
                        help_text="Document key for this Invoice record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "document_sha256",
                    models.CharField(
                        blank=True,
                        help_text="Document sha256 for this Invoice record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency for this Invoice record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "import_row",
                    models.OneToOneField(
                        blank=True,
                        help_text="Import row for this Invoice record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.importrow",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Issued by for this Invoice record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Period for this Invoice record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.academicperiod",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School for this Invoice record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student for this Invoice record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "relationship",
                    models.CharField(
                        default="self",
                        help_text="Relationship for this StudentAccess record.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Status for this StudentAccess record.",
                        max_length=255,
                    ),
                ),
                (
                    "can_pay",
                    models.BooleanField(
                        default=True, help_text="Can pay for this StudentAccess record."
                    ),
                ),
                (
                    "can_view_invoices",
                    models.BooleanField(
                        default=True, help_text="Can view invoices for this StudentAccess record."
                    ),
                ),
                (
                    "can_view_history",
                    models.BooleanField(
                        default=True, help_text="Can view history for this StudentAccess record."
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Requested at for this StudentAccess record.",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Reviewed at for this StudentAccess record.",
                        null=True,
                    ),
                ),
                (
                    "verification_reference",
                    models.CharField(
                        blank=True,
                        help_text="Verification reference for this StudentAccess record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reviewed by for this StudentAccess record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student for this StudentAccess record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User for this StudentAccess record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "amount_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Amount delta for this InvoiceAdjustment record.",
                        max_digits=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        default="", help_text="Reason for this InvoiceAdjustment record."
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        default="",
                        help_text="Source key for this InvoiceAdjustment record.",
                        max_length=255,
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Effective at for this InvoiceAdjustment record.",
                    ),
                ),
                (
                    "document_key",
                    models.CharField(
                        blank=True,
                        help_text="Document key for this InvoiceAdjustment record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        help_text="Approved by for this InvoiceAdjustment record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice for this InvoiceAdjustment record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.invoice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["invoice", "effective_at"], name="fees_invoic_invoice_025b76_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invoice", "source_key"), name="fees_invoiceadjustme_u0"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Position for this InvoiceLine record."
                    ),
                ),
                (
                    "description_snapshot",
                    models.TextField(
                        default="", help_text="Description snapshot for this InvoiceLine record."
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Quantity for this InvoiceLine record.",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Unit amount for this InvoiceLine record.",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "line_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Line amount for this InvoiceLine record.",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for this InvoiceLine record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.feecategory",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice for this InvoiceLine record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.invoice",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schedule for this InvoiceLine record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.feeschedule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invoice", "position"), name="fees_invoiceline_u0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)), name="fees_invoiceline_m0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_amount__gte", 0)), name="fees_invoiceline_m1"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_amount__gte", 0)), name="fees_invoiceline_m2"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["status", "created_at"], name="fees_school_status_0e3eb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeschedule",
            index=models.Index(
                fields=["school", "period", "is_active"], name="fees_feesch_school__fb990b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                fields=("school", "code", "revision"), name="fees_feeschedule_u0"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="fees_feeschedule_m0"
            ),
        ),
        migrations.AddIndex(
            model_name="feecategory",
            index=models.Index(
                fields=["school", "is_active"], name="fees_feecat_school__c947d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feecategory",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="fees_feecategory_u0"
            ),
        ),
        migrations.AddIndex(
            model_name="academicperiod",
            index=models.Index(
                fields=["school", "is_active"], name="fees_academ_school__23c8ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="period_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="fees_academicperiod_u0"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "status", "class_label"], name="fees_studen_school__3d633c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "admission_number"), name="fees_student_u0"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["school", "status", "due_on"], name="fees_invoic_school__0a82f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "issued_at"], name="fees_invoic_student_400b70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(fields=("school", "number"), name="fees_invoice_u0"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)), name="fees_invoice_m0"
            ),
        ),
        migrations.AddIndex(
            model_name="studentaccess",
            index=models.Index(fields=["user", "status"], name="fees_studen_user_id_392cc8_idx"),
        ),
        migrations.AddIndex(
            model_name="studentaccess",
            index=models.Index(fields=["student", "status"], name="fees_studen_student_ec93d9_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relationship", "self"), ("status", "approved")),
                fields=("student",),
                name="one_verified_student_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentaccess",
            constraint=models.UniqueConstraint(
                fields=("student", "user"), name="fees_studentaccess_u0"
            ),
        ),
    ]
