# Generated by Django 5.2.17 on 2026-09-23 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_state_constraints"),
        ("fees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "issued", "void"])),
                name="ck_invoice_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "approved", "rejected", "suspended"])
                ),
                name="ck_school_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "active", "inactive", "rejected"])),
                name="ck_student_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(("relationship__in", ["self", "parent", "guardian", "sponsor"])),
                name="ck_studentaccess_relati",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "approved", "rejected", "revoked"])),
                name="ck_studentaccess_status",
            ),
        ),
    ]
