# Generated by Django 5.2.17 on 2026-09-23 22:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Reference for this SupportTicket record.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="",
                        help_text="Subject for this SupportTicket record.",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Category for this SupportTicket record.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="open",
                        help_text="Status for this SupportTicket record.",
                        max_length=255,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Resolved at for this SupportTicket record.",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned to for this SupportTicket record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        help_text="Opened by for this SupportTicket record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment for this SupportTicket record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="payments.payment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School for this SupportTicket record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "status",
                    models.CharField(
                        default="open",
                        help_text="Status for this ChatConversation record.",
                        max_length=255,
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        blank=True,
                        help_text="Consent version for this ChatConversation record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "retention_until",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Retention until for this ChatConversation record.",
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last activity at for this ChatConversation record.",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School for this ChatConversation record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fees.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User for this ChatConversation record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        blank=True,
                        help_text="Ticket for this ChatConversation record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="support.supportticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "author_kind",
                    models.CharField(
                        default="user",
                        help_text="Author kind for this TicketMessage record.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(default="", help_text="Body for this TicketMessage record."),
                ),
                (
                    "visibility",
                    models.CharField(
                        default="requester",
                        help_text="Visibility for this TicketMessage record.",
                        max_length=255,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Sent at for this TicketMessage record.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Author for this TicketMessage record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Ticket for this TicketMessage record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="support.supportticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque stable record identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="UTC creation timestamp."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="UTC last write timestamp."),
                ),
                (
                    "role",
                    models.CharField(
                        default="", help_text="Role for this ChatMessage record.", max_length=255
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Sequence for this ChatMessage record."
                    ),
                ),
                (
                    "content",
                    models.TextField(default="", help_text="Content for this ChatMessage record."),
                ),
                (
                    "request_key",
                    models.CharField(
                        blank=True,
                        help_text="Request key for this ChatMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed",
                        help_text="Status for this ChatMessage record.",
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider for this ChatMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Model name for this ChatMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upstream_request_id",
                    models.CharField(
                        blank=True,
                        help_text="Upstream request id for this ChatMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token usage for this ChatMessage record.",
                    ),
                ),
                (
                    "redacted_error_code",
                    models.CharField(
                        blank=True,
                        help_text="Redacted error code for this ChatMessage record.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation for this ChatMessage record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="support.chatconversation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"], name="support_cha_convers_68f21b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("request_key__isnull", False)),
                        fields=("conversation", "request_key", "role"),
                        name="chat_request_dedupe",
                    ),
                    models.UniqueConstraint(
                        fields=("conversation", "sequence"), name="support_chatmessage_u0"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["opened_by", "created_at"], name="support_sup_opened__67d65c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["school", "status"], name="support_sup_school__61c69c_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="support_sup_assigne_87974a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user", "last_activity_at"], name="support_cha_user_id_67d28d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(fields=["retention_until"], name="support_cha_retenti_0f437f_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketmessage",
            index=models.Index(fields=["ticket", "sent_at"], name="support_tic_ticket__bb5f68_idx"),
        ),
    ]
