# Generated by Django 5.2.17 on 2026-09-23 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_state_constraints"),
        ("payments", "0002_state_constraints"),
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "closed", "escalated"])),
                name="ck_chatconversation_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["user", "assistant", "system"])),
                name="ck_chatmessage_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "completed", "failed"])),
                name="ck_chatmessage_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["open", "in_progress", "waiting", "resolved", "closed"])
                ),
                name="ck_supportticket_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibility__in", ["requester", "internal"])),
                name="ck_ticketmessage_visibi",
            ),
        ),
    ]
